{% set name = "veridist" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/alisadeghiaghili/veridist/releases/download/v{{ version }}/veridist-{{ version }}.tar.gz
  sha256: 0e37a582f81a6730b0a537ce32d88c94c395e11b14fd5f2c6783b840118abbdd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.11
    - setuptools >=77
  run:
    - numpy >=1.26,<3
    - python >=3.11

test:
  imports:
    - veridist

about:
  home: https://github.com/alisadeghiaghili/veridist
  license: BUSL-1.1
  license_file: LICENSE
  summary: Evidence-first distribution fitting with explicit execution contracts

extra:
  recipe-maintainers:
    - alisadeghiaghili
